Entrega1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include ('app1.urls')),
]

#urls imagenes

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app1/urls.py
from django.urls import path
from app1 import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('',views.inicio, name="inicio"),
    path('aspirantes/',views.AspirantesLista.as_view(), name="aspirantes"),
    path('empleados/',views.EmpleadosLista.as_view(), name="empleados"),
    path('productos/',views.ProductosLista.as_view(), name="productos"),
    path('crearaspirante/',views.formaspirante, name="crearaspirante"),
    path('crearproducto/',views.formproducto, name="crearproducto"),
    path('crearempleado/',views.formempleado, name="crearempleado"),
    path('busquedaemp/',views.buscarempleado, name="busquedaemp"),
    path('busquedaasp/',views.buscaraspirante, name="busquedaasp"),
    path('busquedapro/',views.buscarproducto, name="busquedapro"),
    path('resuemp/',views.busquedaempleado, name="resuemp"),
    path('resuasp/',views.busquedaaspirante, name="resuasp"),
    path('resupro/',views.busquedaproducto, name="resupro"),
    path('login/', views.iniciar_sesion, name = "Login"),
    path('registro/', views.registro, name = "Registro"),
    path('logout/', LogoutView.as_view(template_name="app1/logout.html"), name = "cerrarsesion"),
    path('empleados/<int:pk>', views.EmpleadoDetalle.as_view(), name = "EmpleadoDetalle"),
    path('empleados/editar/<int:pk>', views.EmpleadosUpdate.as_view(), name = "EditarEmpleado"),
    path('empleados/borrar/<int:pk>', views.EmpleadosBorrar.as_view(), name = "BorrarEmpleado"),
    path('productos/<int:pk>', views.ProductosDetalle.as_view(), name = "ProductosDetalle"),
    path('productos/editar/<int:pk>', views.ProductosUpdate.as_view(), name = "EditarProductos"),
    path('productos/borrar/<int:pk>', views.ProductosBorrar.as_view(), name = "BorrarProductos"),
    path('aspirantes/<int:pk>', views.AspirantesDetalle.as_view(), name = "AspirantesDetalle"),
    path('aspirantes/editar/<int:pk>', views.AspirantesUpdate.as_view(), name = "EditarAspirantes"),
    path('aspirantes/borrar/<int:pk>', views.AspirantesBorrar.as_view(), name = "BorrarAspirantes"),
    path('editarUsuarios', views.editarUsuario, name = "editarUsuarios"),
    path("avatar/", views.crearAvatar, name="Avatar"),
    path("acerca/", views.acerca, name="Acerca"),
    path("cuenta/", views.cuenta, name="Cuenta"),
]

app1/models.py
from distutils.command.upload import upload
from django.shortcuts import render
from django.db import models
from django.contrib.auth.models import User

class Productos(models.Model):
    def __str__(self):
        return (f"Producto {self.nombre}, {self.codigo}")
    nombre = models.CharField(max_length=60)
    codigo = models.IntegerField()
    vto = models.DateField()

class Empleados(models.Model):
    def __str__(self):
        return (f"Empleado {self.nombre}, {self.cargos}")
    nombre = models.CharField(max_length=60)
    edad = models.IntegerField()
    cargos = models.CharField(max_length=60)

class Aspirantes(models.Model):
    def __str__(self):
        return (f"Aspirante {self.nombre}, {self.ingreso}")
    nombre = models.CharField(max_length=60)
    edad = models.IntegerField()
    ingreso = models.DateField()

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

app1/views.py
from django.shortcuts import render
from app1.form import FormularioEditarUsuario, Formularioempleado, Formularioproducto, Formularioaspirante, FormularioRegistro, AvatarFormulario
from django.http import HttpResponse
from app1.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView

def inicio(request):
    return render(request, "app1/inicio.html")
@login_required
def empleados(request):
    return render(request, "app1/Empleados_list.html")
@login_required
def aspirantes(request):
    return render(request, "app1/aspirantes.html")
@login_required
def productos(request):
    return render(request, "app1/productos_list.html")
@login_required
def formempleado(request):
      if request.method == "POST":
            
            formulario1 = Formularioempleado(request.POST)
            if formulario1.is_valid():
                  info = formulario1.cleaned_data
                  empleadof = Empleados(nombre = info["nombre"], edad = info["edad"], cargos = info["cargos"])
                  empleadof.save()
                  return render (request, "app1/empleadocreado.html")

      else: 
            formulario1 = Formularioempleado()
            
      return render (request, "app1/crearempleado.html", {"formempleado":formulario1})
@login_required
def formproducto(request):
      if request.method == "POST":
            
            formulario2 = Formularioproducto(request.POST)
            if formulario2.is_valid():
                  info = formulario2.cleaned_data
                  productof = Productos(nombre = info["nombre"], codigo = info["codigo"], vto = info["vto"])
                  productof.save()
                  return render (request, "app1/productocreado.html")

      else: 
            formulario2 = Formularioproducto()
            
      return render (request, "app1/crearproducto.html", {"formproducto":formulario2})
@login_required
def formaspirante(request):
      if request.method == "POST":
            
            formulario3 = Formularioaspirante(request.POST)
            if formulario3.is_valid():
                  info = formulario3.cleaned_data
                  aspirantef = Aspirantes(nombre = info["nombre"], edad = info["edad"], ingreso = info["ingreso"])
                  aspirantef.save()
                  return render (request, "app1/aspirantecreado.html")

      else: 
            formulario3 = Formularioaspirante()
            
      return render (request, "app1/crearaspirante.html", {"formaspirante":formulario3})
@login_required
def buscarempleado(request):
      return render(request, "app1/buscarempleado.html")
@login_required
def buscarproducto(request):
      return render(request, "app1/buscarproducto.html")
@login_required
def buscaraspirante(request):
      return render(request, "app1/buscaraspirante.html")
@login_required
def busquedaempleado(request):
      if request.GET["cargos"]:
            busqueda = request.GET["cargos"]
            empleado =  Empleados.objects.filter(cargos__icontains=busqueda)
            return render(request, "app1/resultadosemp.html", {"empleado":empleado, "busqueda":busqueda})
      else:
            mensaje = "No enviaste datos"
      
      return HttpResponse(mensaje)
@login_required
def busquedaaspirante(request):
      if request.GET["nombre"]:
            busqueda2 = request.GET["nombre"]
            aspirante = Aspirantes.objects.filter(nombre__icontains=busqueda2)
            return render (request, "app1/resultadosasp.html", {"aspirante":aspirante, "busqueda2":busqueda2})
      else:
            respuesta = "No enviaste datos"
      return HttpResponse (respuesta)
@login_required
def busquedaproducto(request):
      if request.GET["nombre"]:
            busqueda3 = request.GET["nombre"]
            producto = Productos.objects.filter(nombre__icontains=busqueda3)
            return render (request, "app1/resultadospro.html", {"producto":producto, "busqueda3":busqueda3})
      else:
            respuesta = "No enviaste datos"
      return HttpResponse (respuesta)

def iniciar_sesion(request):
      if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                  usuario = form.cleaned_data.get("username")
                  contra = form.cleaned_data.get("password")

                  user = authenticate(username=usuario, password=contra) 

                  if user != None:
                        login(request, user)
                        return render (request, "app1/bienvenido.html", {"mensaje":f"Hola {user}"})
            else:
                  return render (request, "app1/bienvenido.html", {"mensaje":f"Datos incorrectos!"})
      
      else:
            form = AuthenticationForm()
      
      return render (request, "app1/login.html", {"formu3":form})

def registro(request):
      if request.method == "POST":
            formu = FormularioRegistro(request.POST)

            if formu.is_valid():
                  nombreUsuario = formu.cleaned_data["username"]
                  formu.save()

                  return render(request, "app1/usuariocreado.html", {"mensaje2": f"Usuario {nombreUsuario} creado!"})

      else:
            formu = FormularioRegistro()

      return render (request, "app1/registro.html", {"formu4":formu})

class EmpleadosLista(ListView):
      model = Empleados
class EmpleadoDetalle(DetailView):
      model = Empleados
class EmpleadosUpdate(UpdateView):
      model = Empleados
      success_url = "/app1/empleados/"
      fields = ["nombre","edad", "cargos"]
      def get(self, request, **kwargs):
        if not self.request.user.has_perm("app1.view_aspirantes"):
            return render(request, "app1/adminrequired.html")
        self.object = self.get_object()
        contexto = self.get_context_data(object=self.object)
        return self.render_to_response(contexto)
class EmpleadosBorrar(DeleteView):
      model = Empleados
      success_url = "/app1/empleados/"
      def get(self, request, **kwargs):
        if not self.request.user.has_perm("app1.view_aspirantes"):
            return render(request, "app1/adminrequired.html")
        self.object = self.get_object()
        contexto = self.get_context_data(object=self.object)
        return self.render_to_response(contexto)


class ProductosLista(ListView):
      model = Productos
class ProductosDetalle(DetailView):
      model = Productos
class ProductosUpdate(UpdateView):
      model = Productos
      success_url = "/app1/productos/"
      fields = ["nombre","codigo", "vto"]
class ProductosBorrar(DeleteView):
      model = Productos
      success_url = "/app1/productos/"

class AspirantesLista(ListView):
      model = Aspirantes
class AspirantesDetalle(DetailView):
      model = Aspirantes
class AspirantesUpdate(UpdateView):
      model = Aspirantes
      success_url = "/app1/aspirantes/"
      fields = ["nombre","edad", "ingreso"]
      def get(self, request, **kwargs):
        if not self.request.user.has_perm("app1.view_aspirantes"):
            return render(request, "app1/adminrequired.html")
        self.object = self.get_object()
        contexto = self.get_context_data(object=self.object)
        return self.render_to_response(contexto)
class AspirantesBorrar(DeleteView):
      model = Aspirantes
      success_url = "/app1/aspirantes/"
      def get(self, request, **kwargs):
        if not self.request.user.has_perm("app1.view_aspirantes"):
            return render(request, "app1/adminrequired.html")
        self.object = self.get_object()
        contexto = self.get_context_data(object=self.object)
        return self.render_to_response(contexto)

@login_required
def editarUsuario(request):
      usuarioConectado = request.user
      
      if request.method == "POST":
            formEdicion = FormularioEditarUsuario(request.POST)
            if formEdicion.is_valid():
                  info = formEdicion.cleaned_data
                  usuarioConectado.email = info["email"]
                  usuarioConectado.password1 = info["password1"]
                  usuarioConectado.password2 = info["password2"]
                  usuarioConectado.first_name = info["first_name"]
                  usuarioConectado.last_name = info["last_name"]

                  usuarioConectado.save()
                  return render(request, "app1/inicio.html")
      else:
            formEdicion = FormularioEditarUsuario(initial = {"email":usuarioConectado.email, "nombre": usuarioConectado.first_name, "apellido":usuarioConectado.last_name})
      contexto = {"formEdicion":formEdicion, "UsuarioNombre":usuarioConectado}
      return render(request, "app1/editarUsuario.html", contexto)

@login_required
def crearAvatar(request):
    if request.method == "POST":
        miformulario = AvatarFormulario(request.POST, request.FILES)
        if miformulario.is_valid():
            usuarioActual = User.objects.get(username=request.user)
            avatar = Avatar(user = usuarioActual, imagen=miformulario.cleaned_data["imagen"])
            avatar.save()
            return render(request, "app1/inicio.html")
    else:
        miformulario = AvatarFormulario()
    return render(request, "app1/crearavatar.html", {"miformulario":miformulario})

def acerca(request):
      return render(request, "app1/acercademi.html")

def cuenta(request):
      return render(request, "app1/cuenta.html")

app1/templates/app1/acercademi.html
{% extends "app1/padre.html" %}

{% block descripcion %}
    <p>Mi nombre es Vallejos Agustin Mateo. Mi idea para el proyecto fue inspirada en las problematicas que atendemos con mi familia en nuestro propio negocio, busca gestionar y tener una minima vision de los productos, empleados y aspirantes a contratar.
        Los usuarios no registrados pueden ver la base de datos de los productos, por si se requiere urgencia en la consulta de informacion básica o actualizarla.
        Se pueden registrar parte del staff para que estos puedan administrar estos aspectos, sin embargo solo el supervisor puede eliminar o editar datos.
        Los usuarios pueden cambiar su avatar cuantas veces quieran, ya que me di cuenta que si ponía "first" en vez de "last" solo quedaba una imagen (la primera puesta) 
        y a su vez ver los datos de su cuenta en el apartado "Cuenta", como asi tambien editarlo en el apartado "Editar Cuenta".</p>
    <a href="{% url 'inicio' %}"><br>Volver</a>
{%endblock%}

app1/templates/app1/aspirantecreado.html
{% extends "app1/padre.html" %}

{% load static %}

{% block pestaña%}
    Aspirante Creado
{% endblock %}

{% block tituloprin%}
    Aspirante Creado
    
{% endblock %}

{% block descripcion%}
    <a href="{% url 'aspirantes' %}">Volver</a>
{% endblock %}

app1/templates/app1/aspirantes_confirm_delete.html
{% extends "app1/padre.html" %}

{% block tituloprin %}
    
Eliminar aspirante
    
{% endblock %}

{% block descripcion %}
<form method="POST"> {% csrf_token %}
    <p>Estás seguro que quieres borrar {{aspirantes.nombre}}</p>
    <input type="submit" value="Confirmar">
</form> 
{% endblock %}

app1/templates/app1/aspirantes_detail.html
{% extends "app1/padre.html" %}

{% block tituloprin %}
 <h1>
    Descripcion
 </h1>   
    
{% endblock %}

{% block descripcion %}
<p>
    Nombre: {{aspirantes.nombre}}
    <br>
    Edad: {{aspirantes.edad}}
    <br>
    Ingreso: {{aspirantes.ingreso}}
</p>
<a href="{% url 'aspirantes' %}">Atrás</a>
{% endblock %}

app1/templates/app1/buscarproducto.html
{% extends "app1/padre.html" %}

{% load static %}

{% block titulo%}
    Busqueda
{% endblock %}

{% block tituloprin%}
    <form action="/app1/resupro/" method="GET">
        <input type="text" name="nombre" id="nombre" value="Nombre">
        <input type="submit" value="Buscar">
    </form>
{% endblock %}

    

app1/templates/app1/crearaspirante.html
{% extends "app1/padre.html" %}

{% load static %}

{% block pestaña%}
    Crear Aspirante
{% endblock %}

{% block tituloprin%}
    <form method="POST"> {% csrf_token%}
        <table>
            {{formaspirante.as_p}}
        </table>
        <input type="submit" value="Crear">
    </form>
    
{% endblock %}

app1/templates/app1/empleadocreado.html
{% extends "app1/padre.html" %}

{% load static %}

{% block pestaña%}
    Empleado Creado
{% endblock %}

{% block tituloprin%}
    Empleado Creado
    
{% endblock %}

{% block descripcion%}
    <a href="{% url 'empleados' %}">Volver</a>
{% endblock %}

app1/templates/app1/empleados_confirm_delete.html
{% extends "app1/padre.html" %}

{% block tituloprin %}
    
Eliminar empleado
    
{% endblock %}

{% block descripcion %}
<form method="POST"> {% csrf_token %}
    <p>Estás seguro que quieres borrar {{empleados.nombre}}</p>
    <input type="submit" value="Confirmar">
</form> 
{% endblock %}

app1/templates/app1/padre.html
<!DOCTYPE html>
<html lang="es-ES">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block pestaña%}
            {% endblock %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app1\css\styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'inicio' %}">Adm. Supermercados Vallejos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Empleados
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'empleados' %}">Ver Empleados</a></li>
                                {% if request.user.is_authenticated%}
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'crearempleado' %}">Crear Empleados</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'aspirantes' %}">Aspirantes</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Stock
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'productos' %}">Todos los productos</a></li>
                            </ul>
                        </li>
                        {% if request.user.is_authenticated%}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Inscripción
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'crearempleado' %}">Inscribir Empleado</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'crearaspirante' %}">Inscribir Aspirante</a></li>
                                <li><a class="dropdown-item" href="{% url 'crearproducto' %}">Inscribir Producto</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Busqueda
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'busquedaemp' %}">Buscar Empleado</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'busquedaasp' %}">Buscar Aspirante</a></li>
                                <li><a class="dropdown-item" href="{% url 'busquedapro' %}">Buscar Producto</a></li>
                            </ul>
                        </li>
                    </ul>
                    {% if request.user.is_authenticated%}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Cuenta</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'Cuenta' %}">Cuenta</a></li>
                                <li><a class="dropdown-item" href="{% url 'editarUsuarios' %}">Editar Cuenta</a></li>
                                <li><a class="dropdown-item" href="{% url 'Avatar' %}">Cambiar Avatar</a></li>
                                <li><a class="dropdown-item" href="{% url 'cerrarsesion' %}">Cerrar Sesión</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Avatar' %}" style="color:grey;">Hola {{user.username}}</a></li>
                        {% with first_image=user.avatar_set.last %}
                            {% if first_image %}
                        <img src="{{first_image.imagen.url}}" style="max-width: 50px">
                            {% endif %}
                        {% endwith %}
                    </ul>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'Registro' %}"><button class="btn btn-outline-dark" type="submit">Registrarse</button></a>
                    <a class="dropdown-item" href="{% url 'Login' %}"><button class="btn btn-outline-dark" type="submit">Iniciar Sesión</button></a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                        {% block tituloprin%}
                        {% endblock %}
                    <p class="lead fw-normal text-white-50 mb-0">
                        {% block descripcion%}
                        {% endblock %}
                    </p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022 &nbsp<a href="{% url 'Acerca' %}">Acerca</a></p></div>
            
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

app1/templates/app1/productocreado.html
{% extends "app1/padre.html" %}

{% load static %}

{% block pestaña%}
    Producto Creado
{% endblock %}

{% block tituloprin%}
    Producto Creado
    
{% endblock %}

{% block descripcion%}
    <a href="{% url 'productos' %}">Volver</a>
{% endblock %}

app1/templates/app1/productos_detail.html
{% extends "app1/padre.html" %}

{% block tituloprin %}
 <h1>
    Descripcion
 </h1>   
    
{% endblock %}

{% block descripcion %}
<p>
    Nombre: {{productos.nombre}}
    <br>
    Código: {{productos.codigo}}
    <br>
    Vto: {{productos.vto}}
</p>
<a href="{% url 'productos' %}">Atrás</a>
{% endblock %}

app1/templates/app1/productos_list.html
{% extends "app1/padre.html" %}

{% block tituloprin %}
    
Lista de Productos
    
{% endblock %}

{% block descripcion %}

    <h1>Los productos son:</h1>
    {% for productos in object_list %}
        <li>Nombre: {{productos.nombre}}</li>
        <button>
            <a href="{% url 'EditarProductos' productos.id %}">Editar</a>
        </button>
        <button>
            <a href="{% url 'ProductosDetalle' productos.id %}">Detalle</a>
        </button>
        <button>
            <a href="{% url 'BorrarProductos' productos.id %}">Borrar</a>
        </button>
    {% endfor %}
    <br>
    <button>
        <a href="{% url 'crearproducto' %}">Crear</a>
    </button>
{% endblock %}

app1/templates/app1/resultadosemp.html
{% extends "app1/padre.html" %}

{% load static %}

{% block titulo%}
    Busqueda
{% endblock %}

{% block tituloprin%}
    Está buscando: {{busqueda}}


{% endblock %}

{% block descripcion %}
    {% for empleados in empleado %}
        <DIV ALIGN=left>
            <ul>
                <li>Nombre: {{empleados.nombre}}</li>
                <li>Edad: {{empleados.edad}}</li>
                <li>Cargos: {{empleados.cargos}}</li>
            </ul>
    </DIV>
    {%endfor%}
{% endblock %}

app1/templates/app1/usuariocreado.html
{% extends "app1/padre.html" %}

{% block descripcion %}
    {{mensaje2}}
    <a href="{% url 'inicio' %}"><br>Volver</a>
{%endblock%}